//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EducationalProgram
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contract.
    /// </summary>
    // *** Start programmer edit section *** (Contract CustomAttributes)

    // *** End programmer edit section *** (Contract CustomAttributes)
    [AutoAltered()]
    [Caption("Контракт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContractE", new string[] {
            "Number as \'Номер договора\'",
            "Description as \'Описание контракта\'"})]
    [View("ContractL", new string[] {
            "Number as \'Номер договора\'",
            "Description as \'Описание контракта\'"})]
    public class Contract : ICSSoft.STORMNET.DataObject
    {
        
        private string fDescription;
        
        private string fPriorities;
        
        private string fNumber;
        
        // *** Start programmer edit section *** (Contract CustomMembers)

        // *** End programmer edit section *** (Contract CustomMembers)

        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Contract.Description CustomAttributes)

        // *** End programmer edit section *** (Contract.Description CustomAttributes)
        [NotNull()]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Contract.Description Get start)

                // *** End programmer edit section *** (Contract.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Contract.Description Get end)

                // *** End programmer edit section *** (Contract.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contract.Description Set start)

                // *** End programmer edit section *** (Contract.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Contract.Description Set end)

                // *** End programmer edit section *** (Contract.Description Set end)
            }
        }
        
        /// <summary>
        /// Priorities.
        /// </summary>
        // *** Start programmer edit section *** (Contract.Priorities CustomAttributes)

        // *** End programmer edit section *** (Contract.Priorities CustomAttributes)
        public virtual string Priorities
        {
            get
            {
                // *** Start programmer edit section *** (Contract.Priorities Get start)

                // *** End programmer edit section *** (Contract.Priorities Get start)
                string result = this.fPriorities;
                // *** Start programmer edit section *** (Contract.Priorities Get end)

                // *** End programmer edit section *** (Contract.Priorities Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contract.Priorities Set start)

                // *** End programmer edit section *** (Contract.Priorities Set start)
                this.fPriorities = value;
                // *** Start programmer edit section *** (Contract.Priorities Set end)

                // *** End programmer edit section *** (Contract.Priorities Set end)
            }
        }
        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Contract.Number CustomAttributes)

        // *** End programmer edit section *** (Contract.Number CustomAttributes)
        [NotNull()]
        public virtual string Number
        {
            get
            {
                // *** Start programmer edit section *** (Contract.Number Get start)

                // *** End programmer edit section *** (Contract.Number Get start)
                string result = this.fNumber;
                // *** Start programmer edit section *** (Contract.Number Get end)

                // *** End programmer edit section *** (Contract.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Contract.Number Set start)

                // *** End programmer edit section *** (Contract.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Contract.Number Set end)

                // *** End programmer edit section *** (Contract.Number Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContractE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContractE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContractE", typeof(IIS.EducationalProgram.Contract));
                }
            }
            
            /// <summary>
            /// "ContractL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContractL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContractL", typeof(IIS.EducationalProgram.Contract));
                }
            }
        }
    }
}
