//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EducationalProgram
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// EduProgram.
    /// </summary>
    // *** Start programmer edit section *** (EduProgram CustomAttributes)

    // *** End programmer edit section *** (EduProgram CustomAttributes)
    [AutoAltered()]
    [Caption("Образовательная программа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EduProgramD", new string[] {
            "Name as \'Название образовательной программы\'",
            "Description as \'Описание\'"})]
    [View("EduProgramE", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "Number as \'Number\'"})]
    public class EduProgram : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fDescription;
        
        private IIS.EducationalProgram.Semestr fSemestr;
        
        // *** Start programmer edit section *** (EduProgram CustomMembers)

        // *** End programmer edit section *** (EduProgram CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (EduProgram.Name CustomAttributes)

        // *** End programmer edit section *** (EduProgram.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (EduProgram.Name Get start)

                // *** End programmer edit section *** (EduProgram.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (EduProgram.Name Get end)

                // *** End programmer edit section *** (EduProgram.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (EduProgram.Name Set start)

                // *** End programmer edit section *** (EduProgram.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (EduProgram.Name Set end)

                // *** End programmer edit section *** (EduProgram.Name Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (EduProgram.Description CustomAttributes)

        // *** End programmer edit section *** (EduProgram.Description CustomAttributes)
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (EduProgram.Description Get start)

                // *** End programmer edit section *** (EduProgram.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (EduProgram.Description Get end)

                // *** End programmer edit section *** (EduProgram.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (EduProgram.Description Set start)

                // *** End programmer edit section *** (EduProgram.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (EduProgram.Description Set end)

                // *** End programmer edit section *** (EduProgram.Description Set end)
            }
        }
        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (EduProgram.Number CustomAttributes)

        // *** End programmer edit section *** (EduProgram.Number CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        public virtual string Number
        {
            get
            {
                // *** Start programmer edit section *** (EduProgram.Number Get)

                return null;
                // *** End programmer edit section *** (EduProgram.Number Get)
            }
            set
            {
                // *** Start programmer edit section *** (EduProgram.Number Set)

                // *** End programmer edit section *** (EduProgram.Number Set)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.EducationalProgram.Semestr.
        /// </summary>
        // *** Start programmer edit section *** (EduProgram.Semestr CustomAttributes)

        // *** End programmer edit section *** (EduProgram.Semestr CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Semestr"})]
        public virtual IIS.EducationalProgram.Semestr Semestr
        {
            get
            {
                // *** Start programmer edit section *** (EduProgram.Semestr Get start)

                // *** End programmer edit section *** (EduProgram.Semestr Get start)
                IIS.EducationalProgram.Semestr result = this.fSemestr;
                // *** Start programmer edit section *** (EduProgram.Semestr Get end)

                // *** End programmer edit section *** (EduProgram.Semestr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (EduProgram.Semestr Set start)

                // *** End programmer edit section *** (EduProgram.Semestr Set start)
                this.fSemestr = value;
                // *** Start programmer edit section *** (EduProgram.Semestr Set end)

                // *** End programmer edit section *** (EduProgram.Semestr Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EduProgramD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EduProgramD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EduProgramD", typeof(IIS.EducationalProgram.EduProgram));
                }
            }
            
            /// <summary>
            /// "EduProgramE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EduProgramE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EduProgramE", typeof(IIS.EducationalProgram.EduProgram));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of EduProgram.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfEduProgram CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfEduProgram CustomAttributes)
    public class DetailArrayOfEduProgram : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.EducationalProgram.DetailArrayOfEduProgram members)

        // *** End programmer edit section *** (IIS.EducationalProgram.DetailArrayOfEduProgram members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type EduProgram by index.
        /// </summary>
        /// <summary>
        /// Adds object with type EduProgram.
        /// </summary>
        public DetailArrayOfEduProgram(IIS.EducationalProgram.Semestr fSemestr) : 
                base(typeof(EduProgram), ((ICSSoft.STORMNET.DataObject)(fSemestr)))
        {
        }
        
        public IIS.EducationalProgram.EduProgram this[int index]
        {
            get
            {
                return ((IIS.EducationalProgram.EduProgram)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.EducationalProgram.EduProgram dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
